services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - db
