name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-frontend:latest
          push: true

      - name: Build and push DB image
        uses: docker/build-push-action@v5
        with:
          context: ./db
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-db:latest
          push: true

      - name: Run Trivy vulnerability scanner on Frontend
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/tp-frontend:latest
          severity: 'HIGH,CRITICAL'

      - name: Run Trivy vulnerability scanner on DB
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/tp-db:latest
          severity: 'HIGH,CRITICAL'

      - name: Snyk Scan Frontend
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: '${{ secrets.DOCKER_USERNAME }}/tp-frontend:latest'
        continue-on-error: true

      - name: Snyk Scan DB
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: '${{ secrets.DOCKER_USERNAME }}/tp-db:latest'
        continue-on-error: true
